import { Business, Category } from '../types';

export const categories: Category[] = [
  { id: '1', name: 'Real Estate', slug: 'real-estate', icon: 'Home' },
  { id: '2', name: 'Tech & IT', slug: 'tech-it', icon: 'Cpu' },
  { id: '3', name: 'Education', slug: 'education', icon: 'BookOpen' },
  { id: '4', name: 'Healthcare', slug: 'healthcare', icon: 'HeartPulse' },
  { id: '5', name: 'Shopping', slug: 'shopping', icon: 'ShoppingBag' },
  { id: '6', name: 'Automobile', slug: 'automobile', icon: 'CarFront' },
  { id: '7', name: 'Food & Dining', slug: 'food-dining', icon: 'Utensils' },
  { id: '8', name: 'Events', slug: 'events', icon: 'CalendarDays' },
  { id: '9', name: 'Tourism', slug: 'tourism', icon: 'Palmtree' },
  { id: '10', name: 'Construction', slug: 'construction', icon: 'HardHat' },
];

export const dummyBusinesses: Business[] = [
  {
    id: '1',
    name: 'Kasaragod Heights Developers',
    slug: 'kasaragod-heights',
    category_id: '1',
    description: 'Premier luxury residential and commercial projects across Kasaragod.',
    address: 'Near New Bus Stand, Kasaragod, Kerala',
    location: 'Kasaragod Town',
    phone: '+91 9876543210',
    whatsapp: '919876543210',
    email: 'info@kheights.com',
    logo_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=700&h=420&fit=crop&q=80'],
    status: 'approved', is_featured: true, rating: 4.8, review_count: 342,
    latitude: 12.4998, longitude: 74.9892,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Coastal Cafe & Bistro',
    slug: 'coastal-cafe',
    category_id: '7',
    description: 'Authentic Malabar flavors mixed with modern continental cuisine near Bekal Fort.',
    address: 'Bekal Fort Road, Pallikkara, Kasaragod',
    location: 'Bekal',
    phone: '+91 9845012345',
    whatsapp: '919845012345',
    logo_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=700&h=420&fit=crop&q=80'],
    status: 'approved', is_featured: true, rating: 4.9, review_count: 856,
    latitude: 12.3833, longitude: 75.0333,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Elite Medicare Center',
    slug: 'elite-medicare',
    category_id: '4',
    description: 'Multi-speciality clinic with advanced diagnostics and compassionate care.',
    address: 'MG Road, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 4994220000',
    logo_url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=700&h=420&fit=crop&q=80'],
    status: 'approved', is_featured: true, rating: 4.7, review_count: 512,
    latitude: 12.5015, longitude: 74.9912,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Skyline Automobiles',
    slug: 'skyline-autos',
    category_id: '6',
    description: 'Authorized luxury car dealership and premium service center.',
    address: 'Kanhangad North, Kasaragod',
    location: 'Kanhangad',
    phone: '+91 9988776655',
    logo_url: 'https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=700&h=420&fit=crop&q=80'],
    status: 'approved', is_featured: false, rating: 4.4, review_count: 128,
    latitude: 12.3167, longitude: 75.0833,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Digital Edge KGD',
    slug: 'digital-edge',
    category_id: '2',
    description: 'Full-stack software & digital marketing solutions for local businesses.',
    address: 'Press Club Building, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9000111222',
    logo_url: 'https://images.unsplash.com/photo-1551288049-bbbda536ad31?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=700&h=420&fit=crop&q=80'],
    status: 'approved', is_featured: false, rating: 4.6, review_count: 89,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Spice Garden Restaurant',
    slug: 'spice-garden',
    category_id: '7',
    description: 'Traditional Kerala thali and Malabar biryani since 2001 in the heart of town.',
    address: 'Palace Road, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9111222333',
    whatsapp: '919111222333',
    logo_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=700&h=420&fit=crop&q=80'],
    status: 'approved', is_featured: false, rating: 4.5, review_count: 634,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Bekal Beach Resort',
    slug: 'bekal-beach-resort',
    category_id: '9',
    description: 'Luxury backwater resort with private beach access and Ayurveda spa.',
    address: 'Bekal, Kasaragod',
    location: 'Bekal',
    phone: '+91 9222333444',
    whatsapp: '919222333444',
    logo_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=700&h=420&fit=crop&q=80'],
    status: 'approved', is_featured: false, rating: 4.9, review_count: 1024,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Apex Academy',
    slug: 'apex-academy',
    category_id: '3',
    description: 'Premier coaching center for competitive exams and skill development.',
    address: 'Vidyanagar, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9998887776',
    logo_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1509062522246-3755977927d7?w=700&h=420&fit=crop&q=80'],
    status: 'approved', is_featured: false, rating: 4.5, review_count: 210,
    created_at: new Date().toISOString(),
  },
];

export const stats = [
  { label: 'Verified Businesses', value: '1,200+' },
  { label: 'Weekly Visitors', value: '45k' },
  { label: 'Total Inquiries', value: '8,500+' },
  { label: 'Happy Customers', value: '12k+' },
];

export const testimonials = [
  {
    name: 'John Abraham',
    role: 'Retail Business Owner',
    content: 'Kasaragod Hub helped me grow my retail business by 40% in just six months. The leads are highly qualified.',
    avatar: 'https://i.pravatar.cc/80?u=john',
  },
  {
    name: 'Sara Moideen',
    role: 'Real Estate Agent',
    content: 'The best platform for showcasing our properties. The inquiry interface is simple and effective.',
    avatar: 'https://i.pravatar.cc/80?u=sara',
  },
  {
    name: 'Arjun V.P.',
    role: 'Local Resident',
    content: 'I use it daily to find services around me. The WhatsApp integration saves so much time.',
    avatar: 'https://i.pravatar.cc/80?u=arjun',
  },
];

// Section-based groupings for category carousel sections
export const featuredSections = [
  {
    id: 'food',
    label: 'Food & Dining',
    icon: 'Utensils',
    businesses: dummyBusinesses.filter(b => b.category_id === '7'),
  },
  {
    id: 'tourism',
    label: 'Tourism & Stays',
    icon: 'Palmtree',
    businesses: dummyBusinesses.filter(b => b.category_id === '9'),
  },
  {
    id: 'realestate',
    label: 'Real Estate',
    icon: 'Home',
    businesses: dummyBusinesses.filter(b => b.category_id === '1'),
  },
  {
    id: 'health',
    label: 'Healthcare',
    icon: 'HeartPulse',
    businesses: dummyBusinesses.filter(b => b.category_id === '4'),
  },
];
