import { Business, Category } from '../types';

export const categories: Category[] = [
  { id: '1', name: 'Real Estate', slug: 'real-estate', icon: 'Home' },
  { id: '2', name: 'Tech & IT', slug: 'tech-it', icon: 'Cpu' },
  { id: '3', name: 'Education', slug: 'education', icon: 'BookOpen' },
  { id: '4', name: 'Healthcare', slug: 'healthcare', icon: 'HeartPulse' },
  { id: '5', name: 'Shopping', slug: 'shopping', icon: 'ShoppingBag' },
  { id: '6', name: 'Automobile', slug: 'automobile', icon: 'CarFront' },
  { id: '7', name: 'Food & Dining', slug: 'food-dining', icon: 'Utensils' },
  { id: '8', name: 'Events', slug: 'events', icon: 'CalendarDays' },
  { id: '9', name: 'Tourism', slug: 'tourism', icon: 'Palmtree' },
  { id: '10', name: 'Construction', slug: 'construction', icon: 'HardHat' },
];

export const weeklyPoll = {
  question: "Best Seafront Dining Spot?",
  options: [
    { label: "Ocean Pearl", votes: 1240 },
    { label: "Bekal Waves", votes: 890 },
    { label: "Coastal Bites", votes: 450 }
  ],
  totalVotes: 2580
};

export const bucketLists = [
  {
    id: '1',
    title: 'The Bekal Tourist Guide',
    description: 'A perfect 24-hour itinerary around the ancient fort and its hidden scenic spots.',
    image: '/assets/guides/bekal-fort.png',
    businessCount: 5
  },
  {
    id: '2',
    title: 'Wedding Destination Gems',
    description: 'Expertly curated list of premium venues and high-end wedding caterers in Kasaragod.',
    image: '/assets/guides/wedding-gems.png',
    businessCount: 8
  },
  {
    id: '3',
    title: 'Hidden Cafe Gems',
    description: 'Discover the most sophisticated coffee spots and minimalist tropical cafes.',
    image: '/assets/guides/cafe-gems.png',
    businessCount: 4
  }
];

export const dummyBusinesses: Business[] = [
  {
    id: '1',
    name: 'Kasaragod Heights Developers',
    slug: 'kasaragod-heights',
    category_id: '1',
    description: 'Premier luxury residential and commercial projects across Kasaragod.',
    address: 'Near New Bus Stand, Kasaragod, Kerala',
    location: 'Kasaragod Town',
    phone: '+91 9876543210',
    whatsapp: '919876543210',
    email: 'info@kheights.com',
    logo_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    price_range: 4,
    rating: 4.8,
    review_count: 342,
    latitude: 12.4998,
    longitude: 74.9892,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Coastal Cafe & Bistro',
    slug: 'coastal-cafe',
    category_id: '7',
    description: 'Authentic Malabar flavors mixed with modern continental cuisine near Bekal Fort.',
    address: 'Bekal Fort Road, Pallikkara, Kasaragod',
    location: 'Bekal',
    phone: '+91 9845012345',
    whatsapp: '919845012345',
    logo_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    price_range: 2,
    rating: 4.9,
    review_count: 856,
    latitude: 12.3833,
    longitude: 75.0333,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Elite Medicare Center',
    slug: 'elite-medicare',
    category_id: '4',
    description: 'Multi-speciality clinic with advanced diagnostics and compassionate care.',
    address: 'MG Road, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 4994220000',
    logo_url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    price_range: 3,
    rating: 4.7,
    review_count: 512,
    latitude: 12.5015,
    longitude: 74.9912,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Skyline Automobiles',
    slug: 'skyline-autos',
    category_id: '6',
    description: 'Authorized luxury car dealership and premium service center.',
    address: 'Kanhangad North, Kasaragod',
    location: 'Kanhangad',
    phone: '+91 9988776655',
    logo_url: 'https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: false,
    price_range: 4,
    rating: 4.4,
    review_count: 128,
    latitude: 12.3167,
    longitude: 75.0833,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Digital Edge KGD',
    slug: 'digital-edge',
    category_id: '2',
    description: 'Full-stack software & digital marketing solutions for local businesses.',
    address: 'Press Club Building, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9000111222',
    logo_url: 'https://images.unsplash.com/photo-1551288049-bbbda536ad31?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    price_range: 2,
    rating: 4.6,
    review_count: 89,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Spice Garden Restaurant',
    slug: 'spice-garden',
    category_id: '7',
    description: 'Traditional Kerala thali and Malabar biryani since 2001 in the heart of town.',
    address: 'Palace Road, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9111222333',
    whatsapp: '919111222333',
    logo_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    price_range: 1,
    rating: 4.5,
    review_count: 634,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Bekal Beach Resort',
    slug: 'bekal-beach-resort',
    category_id: '9',
    description: 'Luxury backwater resort with private beach access and Ayurveda spa.',
    address: 'Bekal, Kasaragod',
    location: 'Bekal',
    phone: '+91 9222333444',
    whatsapp: '919222333444',
    logo_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    price_range: 4,
    rating: 4.9,
    review_count: 1024,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Apex Academy',
    slug: 'apex-academy',
    category_id: '3',
    description: 'Premier coaching center for competitive exams and skill development.',
    address: 'Vidyanagar, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9998887776',
    logo_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1509062522246-37559779277c?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: false,
    price_range: 1,
    rating: 4.5,
    review_count: 210,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Kanhangad Builders',
    slug: 'kanhangad-builders',
    category_id: '10',
    description: 'Specializing in sustainable architecture and modern residential complexes.',
    address: 'Main Road, Kanhangad',
    location: 'Kanhangad',
    phone: '+91 9898001122',
    logo_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1541888946425-d81bb19480c5?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    price_range: 3,
    rating: 4.9,
    review_count: 156,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Malabar Gold & Diamonds',
    slug: 'malabar-gold',
    category_id: '5',
    description: 'Premium jewelry showroom featuring traditional and contemporary designs.',
    address: 'City Tower, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 4994230111',
    logo_url: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    price_range: 4,
    rating: 4.8,
    review_count: 2450,
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Uppala Medicals',
    slug: 'uppala-medicals',
    category_id: '4',
    description: '24/7 pharmacy and diagnostic support center in Northern Kasaragod.',
    address: 'Uppala Junction, Kasaragod',
    location: 'Uppala',
    phone: '+91 9447012345',
    logo_url: 'https://images.unsplash.com/photo-1586015555751-63bb0099342c?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    price_range: 2,
    rating: 4.3,
    review_count: 89,
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'TechHub Solutions',
    slug: 'techhub-solutions',
    category_id: '2',
    description: 'Laptop repairs, custom PC building, and network maintenance.',
    address: 'Press Club Road, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9556001122',
    logo_url: 'https://images.unsplash.com/photo-1597733336794-12d05021d510?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    price_range: 2,
    rating: 4.7,
    review_count: 142,
    created_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Green Field Resorts',
    slug: 'green-field-resorts',
    category_id: '9',
    description: 'Eco-friendly stay surrounded by the lush greenery of Western Ghats foothills.',
    address: 'Vellarikundu, Kasaragod',
    location: 'Cheruvathur',
    phone: '+91 9778001122',
    logo_url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    price_range: 3,
    rating: 4.6,
    review_count: 230,
    created_at: new Date().toISOString(),
  },
  {
    id: '14',
    name: 'Smart Mart Supermarket',
    slug: 'smart-mart',
    category_id: '5',
    description: 'One-stop shop for all your daily needs with home delivery services.',
    address: 'Kanhangad South',
    location: 'Kanhangad',
    phone: '+91 9665001122',
    logo_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    price_range: 1,
    rating: 4.4,
    review_count: 870,
    created_at: new Date().toISOString(),
  },
  {
    id: '15',
    name: 'Modern Engineering Works',
    slug: 'modern-engineering',
    category_id: '10',
    description: 'Precision metal fabrication and industrial hardware supply.',
    address: 'Industrial Estate, Vidyanagar',
    location: 'Kasaragod Town',
    phone: '+91 9334001122',
    logo_url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1504917595217-d4dc5f582bb4?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: false,
    price_range: 3,
    rating: 4.2,
    review_count: 45,
    created_at: new Date().toISOString(),
  },
  {
    id: '16',
    name: 'Ocean Vibes Seafood',
    slug: 'ocean-vibes',
    category_id: '7',
    description: 'Fresh catch from the Arabian sea, prepared with authentic Kasaragod spices.',
    address: 'Near Old Port, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9223001122',
    logo_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    price_range: 2,
    rating: 4.8,
    review_count: 560,
    created_at: new Date().toISOString(),
  },
  {
    id: '17',
    name: 'Safe Travels KGD',
    slug: 'safe-travels',
    category_id: '9',
    description: 'Airport transfers and local sightseeing packages with expert guides.',
    address: 'Kasaragod Railway Station road',
    location: 'Kasaragod Town',
    phone: '+91 9112001122',
    logo_url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    price_range: 2,
    rating: 4.5,
    review_count: 120,
    created_at: new Date().toISOString(),
  },
  {
    id: '18',
    name: 'A-Class Stationery',
    slug: 'aclass-stationery',
    category_id: '5',
    description: 'Wholesale and retail office supplies and academic books.',
    address: 'Bank Road, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9001001122',
    logo_url: 'https://images.unsplash.com/photo-1583484963886-df2bef31d7ae?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: false,
    price_range: 1,
    rating: 4.1,
    review_count: 65,
    created_at: new Date().toISOString(),
  },
  {
    id: '19',
    name: 'Harmony Wellness Spa',
    slug: 'harmony-spa',
    category_id: '4',
    description: 'Traditional Ayurvedic treatments and modern wellness therapy.',
    address: 'Cheruvathur High Road',
    location: 'Cheruvathur',
    phone: '+91 9991001122',
    logo_url: 'https://images.unsplash.com/photo-1544161515-450a56ef4586?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    price_range: 3,
    rating: 4.9,
    review_count: 310,
    created_at: new Date().toISOString(),
  },
  {
    id: '20',
    name: 'Kasaragod Electronics',
    slug: 'kasaragod-electronics',
    category_id: '2',
    description: 'Home appliances showroom featuring top global brands with local support.',
    address: 'MG Road, Kasaragod',
    location: 'Kasaragod Town',
    phone: '+91 9882001122',
    logo_url: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=80&h=80&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1526738549149-8e07eca6c147?w=700&h=420&fit=crop&q=80'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    price_range: 3,
    rating: 4.6,
    review_count: 1240,
    created_at: new Date().toISOString(),
  },
];

export const stats = [
  { label: 'Verified Businesses', value: '1,200+' },
  { label: 'Weekly Visitors', value: '45k' },
  { label: 'Total Inquiries', value: '8,500+' },
  { label: 'Happy Customers', value: '12k+' },
];

export const testimonials = [
  {
    name: 'John Abraham',
    role: 'Retail Business Owner',
    content: 'Kasaragod Hub helped me grow my retail business by 40% in just six months. The leads are highly qualified.',
    avatar: 'https://i.pravatar.cc/80?u=john',
  },
  {
    name: 'Sara Moideen',
    role: 'Real Estate Agent',
    content: 'The best platform for showcasing our properties. The inquiry interface is simple and effective.',
    avatar: 'https://i.pravatar.cc/80?u=sara',
  },
  {
    name: 'Arjun V.P.',
    role: 'Local Resident',
    content: 'I use it daily to find services around me. The WhatsApp integration saves so much time.',
    avatar: 'https://i.pravatar.cc/80?u=arjun',
  },
];

// Section-based groupings for category carousel sections
export const featuredSections = [
  {
    id: 'food',
    label: 'Food & Dining',
    icon: 'Utensils',
    businesses: dummyBusinesses.filter(b => b.category_id === '7'),
  },
  {
    id: 'tourism',
    label: 'Tourism & Stays',
    icon: 'Palmtree',
    businesses: dummyBusinesses.filter(b => b.category_id === '9'),
  },
  {
    id: 'realestate',
    label: 'Real Estate',
    icon: 'Home',
    businesses: dummyBusinesses.filter(b => b.category_id === '1'),
  },
  {
    id: 'health',
    label: 'Healthcare',
    icon: 'HeartPulse',
    businesses: dummyBusinesses.filter(b => b.category_id === '4'),
  },
];
